### ISSUE TITLE
Refactor tests and theming

### ISSUE THREAD

**Issue by karen-sarkisyan** [epam/ketcher#1193]
We need to perform a few housekeeping tasks for better DX and fewer potential bugs down the road:

- [x] Refactor theming (`src/styles` folder) to use TypeScript, use another name for folder instead of `styles`. Check whether we use a good practice of theming with emotion and TS.
- [x] Use a common context provider for mui and Emotion theme, merge themes
- [x] Remove test utils with custom renderer and `test-utils` alias. We will use context providers on per-test basis to be more explicit.
- [x] Rename `testsSetup.ts` ->  `setupTests.ts` to follow react apps naming convention
