### ISSUE TITLE
Show preview popup outside of library

### ISSUE THREAD

**Issue by rrodionov91** [epam/ketcher#2906]
**Background**
The preview popup is clipped by the library window:
<img width="1512" alt="image" src="https://github.com/epam/ketcher/assets/14859362/8dcee41d-6031-453e-a7c1-2c1dbf959b3c">

**Solution**
Show preview popup over all other elements on screen

**Comment by SashaGraves** [comment]
Preview can be shown above all elements inside Liba + canvas, but do not overlap Basic UI of Ketcher

**Comment by nightnick** [comment]
Few fixes to achieve design-implementation consistency:

Card:
- [ ] remove `width`
- [ ] remove `margin`
- [ ] set `height: 44px;`

Card grid (parent div):
- [ ] remove `width`
- [ ] set `grid-template-columns: repeat(auto-fill, minmax(54px, 1fr));`
- [ ] add `grid-gap: 8px;`
  
Main Library Component:
- [ ] set `width: 240px;`

Please don't forget to run a quick sync with design before final merge :)
