### ISSUE TITLE
Macro: Support monomers connection dragging AP

### ISSUE THREAD

**Issue by OlZhur** [epam/ketcher#2925]
**Background**
An attachment point (AP) should have a visual representation to be able to select a specific point.

**Requirements**

Monomers should be connected by a bond for the following cases of monomers connections:
* User clicks on the center of the first monomer and drag a bond to the specific AP of the second monomer. A modal window for selection of free AP should be displayed if the first monomer has more than one free AP
* User clicks on the specific AP of the first monomer, clicks on it and drags a bond to the center of the second monomer. A modal window for selection of free AP should be displayed if the second monomer has more than one free AP
* User clicks on the specific AP of the first monomer and drag a bond to the specific AP of the second monomer

There should be a different visual style for free AP compared to non-free AP.
While monomers are chaining by a bond it needs to rotate both appropriate attachment points to the bond direction. 
When users hover over a bond, both AP should be displayed.

_Warning messages:_
1. Warning for Peptides only: flow R1 to R1 or R2 to R2. 'You have connected monomers with attachment points of the same group'
2. No free attachment points. 'Monomers do not have any attachment points available'

Position of connection points on the monomer - according to mock ups

**Comment by nightnick** [comment]
![Frame 2197](https://github.com/epam/ketcher/assets/27892118/d0ebeee3-4e09-4db6-b108-4d2341beb8e4)
![Frame 2198](https://github.com/epam/ketcher/assets/27892118/d4c3476e-ff6d-42e9-8905-93e1d0ed0061)

**Comment by nightnick** [comment]
Warning and error messages are WIP. Need some correction.

**Comment by nightnick** [comment]
Updated screens
![Frame 2197](https://github.com/epam/ketcher/assets/27892118/e0c6d85b-9739-406e-bc67-f116ec236b57)
![Frame 2198](https://github.com/epam/ketcher/assets/27892118/e3547392-bf33-469c-8286-1eb0e2d19942)

**Comment by nightnick** [comment]
New updated designs:
![Bonds Scenarios](https://github.com/epam/ketcher/assets/27892118/0639c173-491d-485e-a626-6b84a1cebcad)

**Comment by nightnick** [comment]
New designs again:
![Bonds Scenarios_ Improvement (in discussion)](https://github.com/epam/ketcher/assets/27892118/828844ed-118e-409b-af6e-f9854f161e70)

**Comment by OlZhur** [comment]
UPD There is no need to release a bond when there is no free AP (red bond in the screen with the design above). The warning message should appear at the moment of attempting to release a bond.

**Comment by MartaWilliams** [comment]
Tested:

Monomers should be connected by a bond for the following cases of monomers connections:

- [ ] User clicks on the center of the first monomer and drag a bond to the specific AP of the second monomer. A modal window for selection of free AP should be displayed if the first monomer has more than one free AP
![image](https://github.com/epam/ketcher/assets/82752700/508582d8-dacf-4b8a-85db-532266475b3d)
![image](https://github.com/epam/ketcher/assets/82752700/24c661d4-f0b7-484c-b55e-42531bebf53b)

- [ ] User clicks on the specific AP of the first monomer, clicks on it and drags a bond to the center of the second monomer. A modal window for selection of free AP should be displayed if the second monomer has more than one free AP
Result: dragging specific AP of monomers to the centre of the second monomer doesn't cause modal window for selection of free AP

- [ ] User clicks on the specific AP of the first monomer and drag a bond to the specific AP of the second monomer
![2023-11-20_14h57_34](https://github.com/epam/ketcher/assets/82752700/93453fe1-e6fd-478b-808b-f1379542658c)
![2023-11-20_14h56_59](https://github.com/epam/ketcher/assets/82752700/3394f82f-80f7-4bae-a96b-20b41ac14418)

- [ ] There should be a different visual style for free AP compared to non-free AP. 
![image](https://github.com/epam/ketcher/assets/82752700/fb58f3bf-4f1e-4106-b364-d07481200e1d)


- [ ] While monomers are chaining by a bond it needs to rotate both appropriate attachment points to the bond direction.

- [ ] When users hover over a bond, both AP should be displayed.
![image](https://github.com/epam/ketcher/assets/82752700/1a7cfccb-adf5-423d-bea4-6edbd222b957)
Warning messages:

- [ ] Warning for Peptides only: flow R1 to R1 or R2 to R2.
 'You have connected monomers with attachment points of the same group'
![image](https://github.com/epam/ketcher/assets/82752700/e4cd1ebd-87b3-44c5-8b44-b34d29ec80f2)

No free attachment points. 'Monomers do not have any attachment points available'
![image](https://github.com/epam/ketcher/assets/82752700/6ed1abd1-68e9-4c32-ad11-405ffbff6f32)
