### ISSUE TITLE
Autotests: Adding/Removing hydrogens works correct for molecules

### ISSUE THREAD

**Issue by AlexeyGirin** [epam/ketcher#3939]
This task is blocked by:
 - https://github.com/epam/Indigo/issues/1535
 - https://github.com/epam/Indigo/issues/1543
 - https://github.com/epam/Indigo/issues/1547
 - https://github.com/epam/Indigo/issues/1549
 - https://github.com/epam/Indigo/issues/1551
 - https://github.com/epam/ketcher/issues/3903
 - https://github.com/epam/Indigo/issues/1553
 - https://github.com/epam/Indigo/issues/1556
 - https://github.com/epam/Indigo/issues/1557
 - https://github.com/epam/Indigo/issues/1559
 - https://github.com/epam/Indigo/issues/1594
 - https://github.com/epam/Indigo/issues/1635
 - https://github.com/epam/ketcher/issues/3990
 - https://github.com/epam/Indigo/issues/1637
 - https://github.com/epam/Indigo/issues/1638
 - https://github.com/epam/ketcher/issues/3997
 - https://github.com/epam/Indigo/issues/1642
 - https://github.com/epam/Indigo/issues/1643
 - https://github.com/epam/Indigo/issues/1644
 - https://github.com/epam/Indigo/issues/1667
 - https://github.com/epam/Indigo/issues/1626

**Description:**
Bunch of test cases validates that user can add remove hydrogens for molecule(s)
Related implementation tasks: https://github.com/epam/Indigo/issues/1436 and https://github.com/epam/ketcher/issues/3685

### Test case 1:
 - [x] User can expand hydrogens for elements from periodic table (This case is blocked by https://github.com/epam/Indigo/issues/1534)

**Preconditions:**
Clear canvas
Open from file: [PeriodicTable.zip](https://github.com/epam/ketcher/files/14006776/PeriodicTable.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 2:
 - [x] User can expand hydrogens for special atom types (This case is blocked by https://github.com/epam/Indigo/issues/1594)

**Preconditions:**
Clear canvas
Open from file: [All Special Atoms.zip](https://github.com/epam/ketcher/files/14007074/All.Special.Atoms.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas (no hydrogens should be added)
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 3:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Charge" property set

**Preconditions:**
Clear canvas
Open from file: [Any Atom + charges + Simple molecules + charges.zip](https://github.com/epam/ketcher/files/14038029/Any.Atom.%2B.charges.%2B.Simple.molecules.%2B.charges.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas (NO hydrogens should be added) - our behavior is different from Marvin and BOIVIA (approved by @AlexanderSavelyev and Valentin)
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 4:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Exact change" property set

**Preconditions:**
Clear canvas
Open from file: [Any Atom + Exact change Simple molecules + Exact change.zip](https://github.com/epam/ketcher/files/14043029/Any.Atom.%2B.Exact.change.Simple.molecules.%2B.Exact.change.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 5:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Inversions" property set
Blocked by:
 - https://github.com/epam/ketcher/issues/3946

**Preconditions:**
Clear canvas
Open from file: [Any Atom + Inversions Simple molecules + Inversions.zip](https://github.com/epam/ketcher/files/14043063/Any.Atom.%2B.Inversions.Simple.molecules.%2B.Inversions.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 6:
 - [x] User can expand hydrogens for any atoms with "Radical" property set
Blocked by: 
 - https://github.com/epam/Indigo/issues/1555
 - https://github.com/epam/Indigo/issues/1556
 - https://github.com/epam/Indigo/issues/1557
 - https://github.com/epam/Indigo/issues/1553

**Preconditions:**
Clear canvas
Open from file: [Any Atom + Radical.zip](https://github.com/epam/ketcher/files/14043124/Any.Atom.%2B.Radical.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 7:
 - [x] User can expand hydrogens for any atoms with "Valences" property set
Blocked by: 
 - https://github.com/epam/Indigo/issues/1538
 - https://github.com/epam/Indigo/issues/1550
 - https://github.com/epam/Indigo/issues/1551
 - https://github.com/epam/Indigo/issues/1555

**Preconditions:**
Clear canvas
Open from file: [Any Atom + Valences.zip](https://github.com/epam/ketcher/files/14047897/Any.Atom.%2B.Valences.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 8:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Aromatic" query feature set

**Preconditions:**
Clear canvas
Open from file: [Aromaticity - aromatic Aromaticity - aliphatic.zip](https://github.com/epam/ketcher/files/14047922/Aromaticity.-.aromatic.Aromaticity.-.aliphatic.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 9:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Charality" query feature set

**Preconditions:**
Clear canvas
Open from file: [Chirality - Anticlockwise Chirality - Clockwise.zip](https://github.com/epam/ketcher/files/14047936/Chirality.-.Anticlockwise.Chirality.-.Clockwise.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 10:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Connectivity" query feature value set
Blocked by:
 - https://github.com/epam/ketcher/issues/3529

**Preconditions:**
Clear canvas
Open from file: [Connectivity.zip](https://github.com/epam/ketcher/files/14047963/Connectivity.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 11:
 - [x] User can expand hydrogens for any atoms with Custom query value set
Blocked by:
 - https://github.com/epam/Indigo/issues/1788
 - https://github.com/epam/Indigo/issues/1789

**Preconditions:**
Clear canvas
Open from file: [Custom query.zip](https://github.com/epam/ketcher/files/14535550/Custom.query.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 12:
 - [x] User can expand hydrogens for any atoms and simple atoms with "H count" query feature values set

**Preconditions:**
Clear canvas
Open from file: [H count.zip](https://github.com/epam/ketcher/files/14048022/H.count.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 13:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Implicit H count" query feature values set

**Preconditions:**
Clear canvas
Open from file: [Implicit H count.zip](https://github.com/epam/ketcher/files/14048033/Implicit.H.count.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 14:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Alias" general property values set
Blocked by:
- https://github.com/epam/ketcher/issues/3903

**Preconditions:**
Clear canvas
Open from file: [Molecules + Alias.zip](https://github.com/epam/ketcher/files/14048082/Molecules.%2B.Alias.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 15:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Ring bond count" query feature values set
Blocked by:
- https://github.com/epam/Indigo/issues/1559

**Preconditions:**
Clear canvas
Open from file: [Ring bond count.zip](https://github.com/epam/ketcher/files/14048099/Ring.bond.count.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 16:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Ring membership" query feature values set
Blocked by:
- https://github.com/epam/ketcher/issues/3529

**Preconditions:**
Clear canvas
Open from file: [Ring membership.zip](https://github.com/epam/ketcher/files/14048167/Ring.membership.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 17:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Ring size" query feature values set
Blocked by:
- https://github.com/epam/ketcher/issues/3529

**Preconditions:**
Clear canvas
Open from file: [Ring size.zip](https://github.com/epam/ketcher/files/14048203/Ring.size.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 18:
 - [x] User can expand hydrogens for Simple Molecules
Blocked by:
- https://github.com/epam/ketcher/issues/3893

**Preconditions:**
Clear canvas
Open from file: [Simple Molecules.zip](https://github.com/epam/ketcher/files/14048599/Simple.Molecules.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 19:
 - [x] User can expand hydrogens for simple molecule with "Radical" property set
Blocked by: 
 - https://github.com/epam/Indigo/issues/1555
 - https://github.com/epam/Indigo/issues/1556
 - https://github.com/epam/Indigo/issues/1557

**Preconditions:**
Clear canvas
Open from file: [Simple molecules + Radical.zip](https://github.com/epam/ketcher/files/14048630/Simple.molecules.%2B.Radical.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 20:
 - [x] User can expand hydrogens for simple molecules with "Valences" property set
Blocked by: 
 - https://github.com/epam/Indigo/issues/1538
 - https://github.com/epam/Indigo/issues/1550
 - https://github.com/epam/Indigo/issues/1551
 - https://github.com/epam/Indigo/issues/1555

**Preconditions:**
Clear canvas
Open from file: [Simple molecules + Valences.zip](https://github.com/epam/ketcher/files/14048653/Simple.molecules.%2B.Valences.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 21:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Substitution count" query feature values set

**Preconditions:**
Clear canvas
Open from file: [Substitution count.zip](https://github.com/epam/ketcher/files/14048699/Substitution.count.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 22:
 - [x] User can expand hydrogens for any atoms and simple atoms with "Unsaturated" query feature values set

**Preconditions:**
Clear canvas
Open from file: [Unsaturated.zip](https://github.com/epam/ketcher/files/14048769/Unsaturated.zip) (unzip first)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 23:
 - [x] User can expand hydrogens for elements from periodic table having Custom query feature atom on the canvas (This case is blocked by https://github.com/epam/Indigo/issues/1534)

**Preconditions:**
Clear canvas
Open from file (unzip first): [Periodic Table  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14137534/Periodic.Table.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 24:
 - [x] User can expand hydrogens for special atom types having Custom query feature atom on the canvas (This case is blocked by https://github.com/epam/Indigo/issues/1594)

**Preconditions:**
Clear canvas
Open from file (unzip first): [Special Atoms  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14137545/Special.Atoms.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas (no hydrogens should be added)
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 25:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Charge" property set having Custom query feature atom on the canvas 

**Preconditions:**
Clear canvas
Open from file (unzip first): [ANYATO~2.zip](https://github.com/epam/ketcher/files/14137554/ANYATO.2.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas (NO hydrogens should be added) - our behavior is different from Marvin and BOIVIA (approved by @AlexanderSavelyev and Valentin)
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 26:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Exact change" property set having Custom query feature atom on the canvas 

**Preconditions:**
Clear canvas
Open from file (unzip first): [ANYATO~1.zip](https://github.com/epam/ketcher/files/14137560/ANYATO.1.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 27:
 - [x] User can expand hydrogens for simple atom and any atoms types with"Inversions" property set having Custom query feature atom on the canvas 
Blocked by:
 - https://github.com/epam/ketcher/issues/3946

**Preconditions:**
Clear canvas
Open from file (unzip first): [ANYATO~1.zip](https://github.com/epam/ketcher/files/14137569/ANYATO.1.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 28:
 - [x] User can expand hydrogens for any atoms with "Radical" property set having Custom query feature atom on the canvas 
Blocked by: 
 - https://github.com/epam/Indigo/issues/1555
 - https://github.com/epam/Indigo/issues/1556
 - https://github.com/epam/Indigo/issues/1557
 - https://github.com/epam/Indigo/issues/1634

**Preconditions:**
Clear canvas
Open from file (unzip first): [Any Atom + Radical  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14137579/Any.Atom.%2B.Radical.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 29:
 - [x] User can expand hydrogens for any atoms with "Valences" property set having Custom query feature atom on the canvas 
Blocked by: 
 - https://github.com/epam/Indigo/issues/1538
 - https://github.com/epam/Indigo/issues/1550
 - https://github.com/epam/Indigo/issues/1551
 - https://github.com/epam/Indigo/issues/1555

**Preconditions:**
Clear canvas
Open from file (unzip first): [Any Atom + Valences  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14137588/Any.Atom.%2B.Valences.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 30:
 - [x] User can expand hydrogens for Simple Molecules having Custom query feature atom on the canvas 
Blocked by:
- https://github.com/epam/ketcher/issues/3893

**Preconditions:**
Clear canvas
Open from file (unzip first): [Simple Molecules  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14137790/Simple.Molecules.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 31:
 - [x] User can expand hydrogens for any atoms with "Radical" property set having Custom query feature atom on the canvas 
Blocked by: 
 - https://github.com/epam/Indigo/issues/1555
 - https://github.com/epam/Indigo/issues/1556
 - https://github.com/epam/Indigo/issues/1557

**Preconditions:**
Clear canvas
Open from file (unzip first): [SIMPLE~1.zip](https://github.com/epam/ketcher/files/14137794/SIMPLE.1.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 32:
 - [x] User can expand hydrogens for simple molecules with "Valences" property set having Custom query feature atom on the canvas 
Blocked by: 
 - https://github.com/epam/Indigo/issues/1538
 - https://github.com/epam/Indigo/issues/1550
 - https://github.com/epam/Indigo/issues/1551
 - https://github.com/epam/Indigo/issues/1555

**Preconditions:**
Clear canvas
Open from file (unzip first): [SIMPLE~1.zip](https://github.com/epam/ketcher/files/14137801/SIMPLE.1.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 33:
 - [x] User can expand hydrogens for simple molecules with "Alias" property set having Custom query feature atom on the canvas 

**Preconditions:**
Clear canvas
Open from file (unzip first): [Molecules + Alias  with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14535850/Molecules.%2B.Alias.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 34:
 - [x] User can expand hydrogens for simple molecules wrapped into different types on groups
Blocked by: 
 - https://github.com/epam/Indigo/issues/1626

**Preconditions:**
Clear canvas
Open from file (unzip first): [Ordinary Atoms - All Groups.zip](https://github.com/epam/ketcher/files/14205850/Ordinary.Atoms.-.All.Groups.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas

### Test case 35:
 - [x] User can expand hydrogens for simple molecules wrapped into different types on groups with custom query feature atom presented on the canvas
Blocked by: 
 - https://github.com/epam/Indigo/issues/1626

**Preconditions:**
Clear canvas
Open from file (unzip first): [Ordinary Atoms - All Groups - with Custom query feature atom on the canvas.zip](https://github.com/epam/ketcher/files/14205865/Ordinary.Atoms.-.All.Groups.-.with.Custom.query.feature.atom.on.the.canvas.zip)

**Main steps:**
Press Add/Remove explicit hydrogens button
Validate canvas
Press Add/Remove explicit hydrogens button
Validate canvas
